import {MigrationInterface, QueryRunner} from "typeorm";

export class UpdateDatabse1629064532791 implements MigrationInterface {
    name = 'UpdateDatabse1629064532791'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query("ALTER TABLE `projects_atividades_activities` DROP FOREIGN KEY `FK_974392b318d217b62da32052689`");
        await queryRunner.query("ALTER TABLE `projects_atividades_activities` DROP FOREIGN KEY `FK_ce4725a7c540057981eb547c913`");
        await queryRunner.query("ALTER TABLE `projects_avisos_notices` DROP FOREIGN KEY `FK_1e4e71740315261703c33079a4c`");
        await queryRunner.query("ALTER TABLE `projects_avisos_notices` DROP FOREIGN KEY `FK_61ef79a2433639d34fb528aaf72`");
        await queryRunner.query("ALTER TABLE `projects_tags_tags` DROP FOREIGN KEY `FK_0e16f99420fe5a6ae7022afa8b8`");
        await queryRunner.query("ALTER TABLE `projects_tags_tags` DROP FOREIGN KEY `FK_3e919187cc1d287f881fc4f6e4e`");
        await queryRunner.query("ALTER TABLE `users_projetos_projects` DROP FOREIGN KEY `FK_c50fdd1f6925679a3e187b9d2c1`");
        await queryRunner.query("ALTER TABLE `users_projetos_projects` DROP FOREIGN KEY `FK_d4db37310394c13743df4b80978`");
        await queryRunner.query("DROP INDEX `IDX_ce4725a7c540057981eb547c91` ON `projects_atividades_activities`");
        await queryRunner.query("DROP INDEX `IDX_974392b318d217b62da3205268` ON `projects_atividades_activities`");
        await queryRunner.query("DROP INDEX `IDX_1e4e71740315261703c33079a4` ON `projects_avisos_notices`");
        await queryRunner.query("DROP INDEX `IDX_61ef79a2433639d34fb528aaf7` ON `projects_avisos_notices`");
        await queryRunner.query("DROP INDEX `IDX_0e16f99420fe5a6ae7022afa8b` ON `projects_tags_tags`");
        await queryRunner.query("DROP INDEX `IDX_3e919187cc1d287f881fc4f6e4` ON `projects_tags_tags`");
        await queryRunner.query("DROP INDEX `IDX_c50fdd1f6925679a3e187b9d2c` ON `users_projetos_projects`");
        await queryRunner.query("DROP INDEX `IDX_d4db37310394c13743df4b8097` ON `users_projetos_projects`");
        await queryRunner.query("CREATE TABLE `disciplinas` (`id` int NOT NULL AUTO_INCREMENT, `titulo` varchar(255) NOT NULL, `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `projects_disciplina_disciplinas` (`disciplinasId` int NOT NULL, `projectsId` int NOT NULL, PRIMARY KEY (`disciplinasId`, `projectsId`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `projects_disciplinas_relacionadas_disciplinas` (`projectsId` int NOT NULL, `disciplinasId` int NOT NULL, INDEX `IDX_960b3246d9c77e27115d25a68e` (`projectsId`), INDEX `IDX_719413c02395cbc71c6d3cb19a` (`disciplinasId`), PRIMARY KEY (`projectsId`, `disciplinasId`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `activities_user_creator_users` (`activitiesId` int NOT NULL, `usersId` int NOT NULL, `usersEmail` varchar(255) NOT NULL, INDEX `IDX_3c7453ba4344971b2b952a6ac3` (`activitiesId`), INDEX `IDX_3157df03e1c2eeb71f0123fc05` (`usersId`, `usersEmail`), PRIMARY KEY (`activitiesId`, `usersId`, `usersEmail`)) ENGINE=InnoDB");
        await queryRunner.query("ALTER TABLE `questions` DROP COLUMN `nota`");
        await queryRunner.query("ALTER TABLE `questions` DROP COLUMN `titulo`");
        await queryRunner.query("ALTER TABLE `questions` DROP COLUMN `tipo`");
        await queryRunner.query("ALTER TABLE `activities` DROP COLUMN `titulo`");
        await queryRunner.query("ALTER TABLE `activities` DROP COLUMN `descricao`");
        await queryRunner.query("ALTER TABLE `projects_avisos_notices` DROP COLUMN `created_at`");
        await queryRunner.query("ALTER TABLE `questions` ADD `title` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `questions` ADD `idQuestion` int NOT NULL");
        await queryRunner.query("ALTER TABLE `activities` ADD `title` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `activities` ADD `description` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `projects` ADD `turma` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `projects` ADD `disciplina` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `projects` ADD `materiaApoio` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `projects` ADD `tecnologias` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `activities` ADD `titulo` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `activities` ADD `descricao` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `projects_avisos_notices` ADD `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `questions` ADD `titulo` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `questions` ADD `tipo` int NOT NULL");
        await queryRunner.query("ALTER TABLE `questions` ADD `nota` int NOT NULL");
        await queryRunner.query("ALTER TABLE `users_projetos_projects` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `users_projetos_projects` ADD PRIMARY KEY (`usersId`, `projectsId`)");
        await queryRunner.query("ALTER TABLE `projects_avisos_notices` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `projects_avisos_notices` ADD PRIMARY KEY (`projectsId`)");
        await queryRunner.query("ALTER TABLE `users_projetos_projects` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `users_projetos_projects` ADD PRIMARY KEY (`usersId`, `projectsId`)");
        await queryRunner.query("ALTER TABLE `projects_avisos_notices` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `projects_avisos_notices` ADD PRIMARY KEY (`projectsId`, `noticesId`)");
        await queryRunner.query("ALTER TABLE `users_projetos_projects` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `users_projetos_projects` ADD PRIMARY KEY (`usersId`, `projectsId`, `usersEmail`)");
        await queryRunner.query("CREATE INDEX `IDX_9e52bef38227dad18c3596a6ae` ON `activities_questions_questions` (`activitiesId`)");
        await queryRunner.query("CREATE INDEX `IDX_4fe4be36c0389b6153ebadd1bc` ON `activities_questions_questions` (`questionsId`)");
        await queryRunner.query("CREATE INDEX `IDX_0e16f99420fe5a6ae7022afa8b` ON `projects_tags_tags` (`projectsId`)");
        await queryRunner.query("CREATE INDEX `IDX_3e919187cc1d287f881fc4f6e4` ON `projects_tags_tags` (`tagsId`)");
        await queryRunner.query("CREATE INDEX `IDX_1e4e71740315261703c33079a4` ON `projects_avisos_notices` (`projectsId`)");
        await queryRunner.query("CREATE INDEX `IDX_61ef79a2433639d34fb528aaf7` ON `projects_avisos_notices` (`noticesId`)");
        await queryRunner.query("CREATE INDEX `IDX_ce4725a7c540057981eb547c91` ON `projects_atividades_activities` (`projectsId`)");
        await queryRunner.query("CREATE INDEX `IDX_974392b318d217b62da3205268` ON `projects_atividades_activities` (`activitiesId`)");
        await queryRunner.query("CREATE INDEX `IDX_c50fdd1f6925679a3e187b9d2c` ON `users_projetos_projects` (`usersId`, `usersEmail`)");
        await queryRunner.query("CREATE INDEX `IDX_d4db37310394c13743df4b8097` ON `users_projetos_projects` (`projectsId`)");
        await queryRunner.query("ALTER TABLE `activities_questions_questions` ADD CONSTRAINT `FK_9e52bef38227dad18c3596a6ae1` FOREIGN KEY (`activitiesId`) REFERENCES `activities`(`id`) ON DELETE CASCADE ON UPDATE CASCADE");
        await queryRunner.query("ALTER TABLE `activities_questions_questions` ADD CONSTRAINT `FK_4fe4be36c0389b6153ebadd1bcb` FOREIGN KEY (`questionsId`) REFERENCES `questions`(`id`) ON DELETE CASCADE ON UPDATE CASCADE");
        await queryRunner.query("ALTER TABLE `projects_tags_tags` ADD CONSTRAINT `FK_0e16f99420fe5a6ae7022afa8b8` FOREIGN KEY (`projectsId`) REFERENCES `projects`(`id`) ON DELETE CASCADE ON UPDATE CASCADE");
        await queryRunner.query("ALTER TABLE `projects_tags_tags` ADD CONSTRAINT `FK_3e919187cc1d287f881fc4f6e4e` FOREIGN KEY (`tagsId`) REFERENCES `tags`(`id`) ON DELETE CASCADE ON UPDATE CASCADE");
        await queryRunner.query("ALTER TABLE `projects_disciplinas_relacionadas_disciplinas` ADD CONSTRAINT `FK_960b3246d9c77e27115d25a68e2` FOREIGN KEY (`projectsId`) REFERENCES `projects`(`id`) ON DELETE CASCADE ON UPDATE CASCADE");
        await queryRunner.query("ALTER TABLE `projects_disciplinas_relacionadas_disciplinas` ADD CONSTRAINT `FK_719413c02395cbc71c6d3cb19ab` FOREIGN KEY (`disciplinasId`) REFERENCES `disciplinas`(`id`) ON DELETE CASCADE ON UPDATE CASCADE");
        await queryRunner.query("ALTER TABLE `projects_avisos_notices` ADD CONSTRAINT `FK_1e4e71740315261703c33079a4c` FOREIGN KEY (`projectsId`) REFERENCES `projects`(`id`) ON DELETE CASCADE ON UPDATE CASCADE");
        await queryRunner.query("ALTER TABLE `projects_avisos_notices` ADD CONSTRAINT `FK_61ef79a2433639d34fb528aaf72` FOREIGN KEY (`noticesId`) REFERENCES `notices`(`id`) ON DELETE CASCADE ON UPDATE CASCADE");
        await queryRunner.query("ALTER TABLE `projects_atividades_activities` ADD CONSTRAINT `FK_ce4725a7c540057981eb547c913` FOREIGN KEY (`projectsId`) REFERENCES `projects`(`id`) ON DELETE CASCADE ON UPDATE CASCADE");
        await queryRunner.query("ALTER TABLE `projects_atividades_activities` ADD CONSTRAINT `FK_974392b318d217b62da32052689` FOREIGN KEY (`activitiesId`) REFERENCES `activities`(`id`) ON DELETE CASCADE ON UPDATE CASCADE");
        await queryRunner.query("ALTER TABLE `users_projetos_projects` ADD CONSTRAINT `FK_c50fdd1f6925679a3e187b9d2c1` FOREIGN KEY (`usersId`, `usersEmail`) REFERENCES `users`(`id`,`email`) ON DELETE CASCADE ON UPDATE CASCADE");
        await queryRunner.query("ALTER TABLE `users_projetos_projects` ADD CONSTRAINT `FK_d4db37310394c13743df4b80978` FOREIGN KEY (`projectsId`) REFERENCES `projects`(`id`) ON DELETE CASCADE ON UPDATE CASCADE");
        await queryRunner.query("ALTER TABLE `activities_user_creator_users` ADD CONSTRAINT `FK_3c7453ba4344971b2b952a6ac34` FOREIGN KEY (`activitiesId`) REFERENCES `activities`(`id`) ON DELETE CASCADE ON UPDATE CASCADE");
        await queryRunner.query("ALTER TABLE `activities_user_creator_users` ADD CONSTRAINT `FK_3157df03e1c2eeb71f0123fc050` FOREIGN KEY (`usersId`, `usersEmail`) REFERENCES `users`(`id`,`email`) ON DELETE CASCADE ON UPDATE CASCADE");
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query("ALTER TABLE `activities_user_creator_users` DROP FOREIGN KEY `FK_3157df03e1c2eeb71f0123fc050`");
        await queryRunner.query("ALTER TABLE `activities_user_creator_users` DROP FOREIGN KEY `FK_3c7453ba4344971b2b952a6ac34`");
        await queryRunner.query("ALTER TABLE `users_projetos_projects` DROP FOREIGN KEY `FK_d4db37310394c13743df4b80978`");
        await queryRunner.query("ALTER TABLE `users_projetos_projects` DROP FOREIGN KEY `FK_c50fdd1f6925679a3e187b9d2c1`");
        await queryRunner.query("ALTER TABLE `projects_atividades_activities` DROP FOREIGN KEY `FK_974392b318d217b62da32052689`");
        await queryRunner.query("ALTER TABLE `projects_atividades_activities` DROP FOREIGN KEY `FK_ce4725a7c540057981eb547c913`");
        await queryRunner.query("ALTER TABLE `projects_avisos_notices` DROP FOREIGN KEY `FK_61ef79a2433639d34fb528aaf72`");
        await queryRunner.query("ALTER TABLE `projects_avisos_notices` DROP FOREIGN KEY `FK_1e4e71740315261703c33079a4c`");
        await queryRunner.query("ALTER TABLE `projects_disciplinas_relacionadas_disciplinas` DROP FOREIGN KEY `FK_719413c02395cbc71c6d3cb19ab`");
        await queryRunner.query("ALTER TABLE `projects_disciplinas_relacionadas_disciplinas` DROP FOREIGN KEY `FK_960b3246d9c77e27115d25a68e2`");
        await queryRunner.query("ALTER TABLE `projects_tags_tags` DROP FOREIGN KEY `FK_3e919187cc1d287f881fc4f6e4e`");
        await queryRunner.query("ALTER TABLE `projects_tags_tags` DROP FOREIGN KEY `FK_0e16f99420fe5a6ae7022afa8b8`");
        await queryRunner.query("ALTER TABLE `activities_questions_questions` DROP FOREIGN KEY `FK_4fe4be36c0389b6153ebadd1bcb`");
        await queryRunner.query("ALTER TABLE `activities_questions_questions` DROP FOREIGN KEY `FK_9e52bef38227dad18c3596a6ae1`");
        await queryRunner.query("DROP INDEX `IDX_d4db37310394c13743df4b8097` ON `users_projetos_projects`");
        await queryRunner.query("DROP INDEX `IDX_c50fdd1f6925679a3e187b9d2c` ON `users_projetos_projects`");
        await queryRunner.query("DROP INDEX `IDX_974392b318d217b62da3205268` ON `projects_atividades_activities`");
        await queryRunner.query("DROP INDEX `IDX_ce4725a7c540057981eb547c91` ON `projects_atividades_activities`");
        await queryRunner.query("DROP INDEX `IDX_61ef79a2433639d34fb528aaf7` ON `projects_avisos_notices`");
        await queryRunner.query("DROP INDEX `IDX_1e4e71740315261703c33079a4` ON `projects_avisos_notices`");
        await queryRunner.query("DROP INDEX `IDX_3e919187cc1d287f881fc4f6e4` ON `projects_tags_tags`");
        await queryRunner.query("DROP INDEX `IDX_0e16f99420fe5a6ae7022afa8b` ON `projects_tags_tags`");
        await queryRunner.query("DROP INDEX `IDX_4fe4be36c0389b6153ebadd1bc` ON `activities_questions_questions`");
        await queryRunner.query("DROP INDEX `IDX_9e52bef38227dad18c3596a6ae` ON `activities_questions_questions`");
        await queryRunner.query("ALTER TABLE `users_projetos_projects` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `users_projetos_projects` ADD PRIMARY KEY (`usersId`, `projectsId`)");
        await queryRunner.query("ALTER TABLE `projects_avisos_notices` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `projects_avisos_notices` ADD PRIMARY KEY (`projectsId`)");
        await queryRunner.query("ALTER TABLE `users_projetos_projects` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `users_projetos_projects` ADD PRIMARY KEY (`usersId`, `usersEmail`, `projectsId`)");
        await queryRunner.query("ALTER TABLE `projects_avisos_notices` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `projects_avisos_notices` ADD PRIMARY KEY (`projectsId`, `noticesId`)");
        await queryRunner.query("ALTER TABLE `users_projetos_projects` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `users_projetos_projects` ADD PRIMARY KEY (`usersId`, `usersEmail`, `projectsId`)");
        await queryRunner.query("ALTER TABLE `questions` DROP COLUMN `nota`");
        await queryRunner.query("ALTER TABLE `questions` DROP COLUMN `tipo`");
        await queryRunner.query("ALTER TABLE `questions` DROP COLUMN `titulo`");
        await queryRunner.query("ALTER TABLE `projects_avisos_notices` DROP COLUMN `created_at`");
        await queryRunner.query("ALTER TABLE `activities` DROP COLUMN `descricao`");
        await queryRunner.query("ALTER TABLE `activities` DROP COLUMN `titulo`");
        await queryRunner.query("ALTER TABLE `projects` DROP COLUMN `tecnologias`");
        await queryRunner.query("ALTER TABLE `projects` DROP COLUMN `materiaApoio`");
        await queryRunner.query("ALTER TABLE `projects` DROP COLUMN `disciplina`");
        await queryRunner.query("ALTER TABLE `projects` DROP COLUMN `turma`");
        await queryRunner.query("ALTER TABLE `activities` DROP COLUMN `description`");
        await queryRunner.query("ALTER TABLE `activities` DROP COLUMN `title`");
        await queryRunner.query("ALTER TABLE `questions` DROP COLUMN `idQuestion`");
        await queryRunner.query("ALTER TABLE `questions` DROP COLUMN `title`");
        await queryRunner.query("ALTER TABLE `projects_avisos_notices` ADD `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `activities` ADD `descricao` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `activities` ADD `titulo` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `questions` ADD `tipo` int NOT NULL");
        await queryRunner.query("ALTER TABLE `questions` ADD `titulo` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `questions` ADD `nota` int NOT NULL");
        await queryRunner.query("DROP INDEX `IDX_3157df03e1c2eeb71f0123fc05` ON `activities_user_creator_users`");
        await queryRunner.query("DROP INDEX `IDX_3c7453ba4344971b2b952a6ac3` ON `activities_user_creator_users`");
        await queryRunner.query("DROP TABLE `activities_user_creator_users`");
        await queryRunner.query("DROP INDEX `IDX_719413c02395cbc71c6d3cb19a` ON `projects_disciplinas_relacionadas_disciplinas`");
        await queryRunner.query("DROP INDEX `IDX_960b3246d9c77e27115d25a68e` ON `projects_disciplinas_relacionadas_disciplinas`");
        await queryRunner.query("DROP TABLE `projects_disciplinas_relacionadas_disciplinas`");
        await queryRunner.query("DROP TABLE `projects_disciplina_disciplinas`");
        await queryRunner.query("DROP TABLE `disciplinas`");
        await queryRunner.query("CREATE INDEX `IDX_d4db37310394c13743df4b8097` ON `users_projetos_projects` (`projectsId`)");
        await queryRunner.query("CREATE INDEX `IDX_c50fdd1f6925679a3e187b9d2c` ON `users_projetos_projects` (`usersId`, `usersEmail`)");
        await queryRunner.query("CREATE INDEX `IDX_3e919187cc1d287f881fc4f6e4` ON `projects_tags_tags` (`tagsId`)");
        await queryRunner.query("CREATE INDEX `IDX_0e16f99420fe5a6ae7022afa8b` ON `projects_tags_tags` (`projectsId`)");
        await queryRunner.query("CREATE INDEX `IDX_61ef79a2433639d34fb528aaf7` ON `projects_avisos_notices` (`noticesId`)");
        await queryRunner.query("CREATE INDEX `IDX_1e4e71740315261703c33079a4` ON `projects_avisos_notices` (`projectsId`)");
        await queryRunner.query("CREATE INDEX `IDX_974392b318d217b62da3205268` ON `projects_atividades_activities` (`activitiesId`)");
        await queryRunner.query("CREATE INDEX `IDX_ce4725a7c540057981eb547c91` ON `projects_atividades_activities` (`projectsId`)");
        await queryRunner.query("ALTER TABLE `users_projetos_projects` ADD CONSTRAINT `FK_d4db37310394c13743df4b80978` FOREIGN KEY (`projectsId`) REFERENCES `projects`(`id`) ON DELETE CASCADE ON UPDATE CASCADE");
        await queryRunner.query("ALTER TABLE `users_projetos_projects` ADD CONSTRAINT `FK_c50fdd1f6925679a3e187b9d2c1` FOREIGN KEY (`usersId`, `usersEmail`) REFERENCES `users`(`id`,`email`) ON DELETE CASCADE ON UPDATE CASCADE");
        await queryRunner.query("ALTER TABLE `projects_tags_tags` ADD CONSTRAINT `FK_3e919187cc1d287f881fc4f6e4e` FOREIGN KEY (`tagsId`) REFERENCES `tags`(`id`) ON DELETE CASCADE ON UPDATE CASCADE");
        await queryRunner.query("ALTER TABLE `projects_tags_tags` ADD CONSTRAINT `FK_0e16f99420fe5a6ae7022afa8b8` FOREIGN KEY (`projectsId`) REFERENCES `projects`(`id`) ON DELETE CASCADE ON UPDATE CASCADE");
        await queryRunner.query("ALTER TABLE `projects_avisos_notices` ADD CONSTRAINT `FK_61ef79a2433639d34fb528aaf72` FOREIGN KEY (`noticesId`) REFERENCES `notices`(`id`) ON DELETE CASCADE ON UPDATE CASCADE");
        await queryRunner.query("ALTER TABLE `projects_avisos_notices` ADD CONSTRAINT `FK_1e4e71740315261703c33079a4c` FOREIGN KEY (`projectsId`) REFERENCES `projects`(`id`) ON DELETE CASCADE ON UPDATE CASCADE");
        await queryRunner.query("ALTER TABLE `projects_atividades_activities` ADD CONSTRAINT `FK_ce4725a7c540057981eb547c913` FOREIGN KEY (`projectsId`) REFERENCES `projects`(`id`) ON DELETE CASCADE ON UPDATE CASCADE");
        await queryRunner.query("ALTER TABLE `projects_atividades_activities` ADD CONSTRAINT `FK_974392b318d217b62da32052689` FOREIGN KEY (`activitiesId`) REFERENCES `activities`(`id`) ON DELETE CASCADE ON UPDATE CASCADE");
    }

}
