import {MigrationInterface, QueryRunner} from "typeorm";

export class resetingDatabse1636317950449 implements MigrationInterface {
    name = 'resetingDatabse1636317950449'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`atollase_db_lucas\`.\`questions\` (\`id\` int NOT NULL AUTO_INCREMENT, \`title\` varchar(255) NOT NULL, \`idQuestion\` int NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`atollase_db_lucas\`.\`activities\` (\`id\` int NOT NULL AUTO_INCREMENT, \`title\` varchar(255) NOT NULL, \`description\` varchar(255) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`atollase_db_lucas\`.\`tags\` (\`id\` int NOT NULL AUTO_INCREMENT, \`titulo\` varchar(255) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`atollase_db_lucas\`.\`notices\` (\`id\` int NOT NULL AUTO_INCREMENT, \`titulo\` varchar(255) NOT NULL, \`descricao\` varchar(255) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`atollase_db_lucas\`.\`disciplinas\` (\`id\` int NOT NULL AUTO_INCREMENT, \`titulo\` varchar(255) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`atollase_db_lucas\`.\`projects\` (\`id\` int NOT NULL AUTO_INCREMENT, \`titulo\` varchar(255) NOT NULL, \`turma\` varchar(255) NOT NULL, \`disciplina\` varchar(255) NOT NULL, \`materiaApoio\` varchar(255) NOT NULL, \`tecnologias\` varchar(255) NOT NULL, \`descricao\` varchar(255) NOT NULL, \`objetivo\` varchar(255) NOT NULL, \`status\` text NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`userCreatorId\` int NULL, \`userCreatorEmail\` varchar(255) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`atollase_db_lucas\`.\`users\` (\`id\` int NOT NULL AUTO_INCREMENT, \`first_name\` varchar(255) NOT NULL, \`last_name\` varchar(255) NOT NULL, \`nickname\` varchar(255) NOT NULL, \`email\` varchar(255) NOT NULL, \`password\` varchar(255) NOT NULL, \`user_type\` int NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`, \`email\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`atollase_db_lucas\`.\`activities_questions_questions\` (\`activitiesId\` int NOT NULL, \`questionsId\` int NOT NULL, PRIMARY KEY (\`activitiesId\`, \`questionsId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`atollase_db_lucas\`.\`disciplinasEscopo\` (\`id\` int NOT NULL AUTO_INCREMENT, \`disciplinas\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`atollase_db_lucas\`.\`Steam\` (\`id\` int NOT NULL AUTO_INCREMENT, \`steam\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`atollase_db_lucas\`.\`ods\` (\`id\` int NOT NULL AUTO_INCREMENT, \`ods\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`atollase_db_lucas\`.\`skills\` (\`id\` int NOT NULL AUTO_INCREMENT, \`skill\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`atollase_db_lucas\`.\`escopo\` (\`id\` int NOT NULL AUTO_INCREMENT, \`disciplina\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`atollase_db_lucas\`.\`escopo_disciplinas\` (\`EscopoId\` int NOT NULL, \`OdsId\` int NOT NULL, PRIMARY KEY (\`EscopoId\`, \`OdsId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`atollase_db_lucas\`.\`escopo_ods\` (\`EscopoId\` int NOT NULL, \`OdsId\` int NOT NULL, PRIMARY KEY (\`EscopoId\`, \`OdsId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`atollase_db_lucas\`.\`escopo_Skills\` (\`escopoId\` int NOT NULL, \`SkillsId\` int NOT NULL, PRIMARY KEY (\`escopoId\`, \`SkillsId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`atollase_db_lucas\`.\`Escopo_Steam\` (\`escopoId\` int NOT NULL, \`SteamId\` int NOT NULL, PRIMARY KEY (\`escopoId\`, \`SteamId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`atollase_db_lucas\`.\`projects_atividades_activities\` (\`projectsId\` int NOT NULL, \`activitiesId\` int NOT NULL, PRIMARY KEY (\`projectsId\`, \`activitiesId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`atollase_db_lucas\`.\`projects_avisos_notices\` (\`projectsId\` int NOT NULL, \`noticesId\` int NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`projectsId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`atollase_db_lucas\`.\`projects_disciplina_disciplinas\` (\`disciplinasId\` int NOT NULL, \`projectsId\` int NOT NULL, PRIMARY KEY (\`disciplinasId\`, \`projectsId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`atollase_db_lucas\`.\`projeto_escopo\` (\`projectsId\` int NOT NULL, \`escopoId\` int NOT NULL, PRIMARY KEY (\`projectsId\`, \`escopoId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`atollase_db_lucas\`.\`projects_tags_tags\` (\`tagsId\` int NOT NULL, \`projectsId\` int NOT NULL, PRIMARY KEY (\`tagsId\`, \`projectsId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`atollase_db_lucas\`.\`projeto_tecnologia\` (\`projectId\` int NOT NULL, \`tecnologiaId\` int NOT NULL, PRIMARY KEY (\`projectId\`, \`tecnologiaId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`atollase_db_lucas\`.\`answers\` (\`id\` int NOT NULL AUTO_INCREMENT, \`resposta\` varchar(255) NOT NULL, \`nota\` int NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`atollase_db_lucas\`.\`tecnologias\` (\`id\` int NOT NULL AUTO_INCREMENT, \`tecnologia\` varchar(255) NOT NULL, \`Links\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`atollase_db_lucas\`.\`users_projetos_projects\` (\`usersId\` int NOT NULL, \`usersEmail\` varchar(255) NOT NULL, \`projectsId\` int NOT NULL, PRIMARY KEY (\`usersId\`, \`projectsId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`atollase_db_lucas\`.\`projects_disciplinas_relacionadas_disciplinas\` (\`projectsId\` int NOT NULL, \`disciplinasId\` int NOT NULL, INDEX \`IDX_960b3246d9c77e27115d25a68e\` (\`projectsId\`), INDEX \`IDX_719413c02395cbc71c6d3cb19a\` (\`disciplinasId\`), PRIMARY KEY (\`projectsId\`, \`disciplinasId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`atollase_db_lucas\`.\`activities_user_creator_users\` (\`activitiesId\` int NOT NULL, \`usersId\` int NOT NULL, \`usersEmail\` varchar(255) NOT NULL, INDEX \`IDX_3c7453ba4344971b2b952a6ac3\` (\`activitiesId\`), INDEX \`IDX_3157df03e1c2eeb71f0123fc05\` (\`usersId\`, \`usersEmail\`), PRIMARY KEY (\`activitiesId\`, \`usersId\`, \`usersEmail\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`atollase_db_lucas\`.\`escopo_steam_steam\` (\`escopoId\` int NOT NULL, \`steamId\` int NOT NULL, INDEX \`IDX_955d7b3be95dfd1edc98613763\` (\`escopoId\`), INDEX \`IDX_2ae07b5b2a16eaaf18bb173d2d\` (\`steamId\`), PRIMARY KEY (\`escopoId\`, \`steamId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`atollase_db_lucas\`.\`answers_questions_questions\` (\`answersId\` int NOT NULL, \`questionsId\` int NOT NULL, INDEX \`IDX_3367d6f77c1fcdcefff2022bf4\` (\`answersId\`), INDEX \`IDX_f5301e03552e125b3a7466abdb\` (\`questionsId\`), PRIMARY KEY (\`answersId\`, \`questionsId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`atollase_db_lucas\`.\`answers_user_creator_users\` (\`answersId\` int NOT NULL, \`usersId\` int NOT NULL, \`usersEmail\` varchar(255) NOT NULL, INDEX \`IDX_8305e4d21af7fe8895df34786b\` (\`answersId\`), INDEX \`IDX_5d25d2520390bc1aa5007d4725\` (\`usersId\`, \`usersEmail\`), PRIMARY KEY (\`answersId\`, \`usersId\`, \`usersEmail\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`activities\` DROP COLUMN \`title\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`activities\` DROP COLUMN \`description\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`questions\` DROP COLUMN \`title\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`questions\` DROP COLUMN \`idQuestion\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`projects_avisos_notices\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`questions\` ADD \`title\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`questions\` ADD \`idQuestion\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`activities\` ADD \`title\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`activities\` ADD \`description\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`activities\` ADD \`titulo\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`activities\` ADD \`descricao\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`projects_avisos_notices\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`questions\` ADD \`titulo\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`questions\` ADD \`tipo\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`questions\` ADD \`nota\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`projects_avisos_notices\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`projects_avisos_notices\` ADD PRIMARY KEY (\`projectsId\`, \`noticesId\`)`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`users_projetos_projects\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`users_projetos_projects\` ADD PRIMARY KEY (\`usersId\`, \`usersEmail\`, \`projectsId\`)`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`projects_avisos_notices\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`projects_avisos_notices\` ADD PRIMARY KEY (\`projectsId\`)`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`users_projetos_projects\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`users_projetos_projects\` ADD PRIMARY KEY (\`usersId\`, \`projectsId\`)`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`projects_avisos_notices\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`projects_avisos_notices\` ADD PRIMARY KEY (\`projectsId\`, \`noticesId\`)`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`users_projetos_projects\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`users_projetos_projects\` ADD PRIMARY KEY (\`usersId\`, \`projectsId\`, \`usersEmail\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_9e52bef38227dad18c3596a6ae\` ON \`atollase_db_lucas\`.\`activities_questions_questions\` (\`activitiesId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_4fe4be36c0389b6153ebadd1bc\` ON \`atollase_db_lucas\`.\`activities_questions_questions\` (\`questionsId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_0e16f99420fe5a6ae7022afa8b\` ON \`atollase_db_lucas\`.\`projects_tags_tags\` (\`projectsId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_3e919187cc1d287f881fc4f6e4\` ON \`atollase_db_lucas\`.\`projects_tags_tags\` (\`tagsId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_1e4e71740315261703c33079a4\` ON \`atollase_db_lucas\`.\`projects_avisos_notices\` (\`projectsId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_61ef79a2433639d34fb528aaf7\` ON \`atollase_db_lucas\`.\`projects_avisos_notices\` (\`noticesId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_ce4725a7c540057981eb547c91\` ON \`atollase_db_lucas\`.\`projects_atividades_activities\` (\`projectsId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_974392b318d217b62da3205268\` ON \`atollase_db_lucas\`.\`projects_atividades_activities\` (\`activitiesId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_c50fdd1f6925679a3e187b9d2c\` ON \`atollase_db_lucas\`.\`users_projetos_projects\` (\`usersId\`, \`usersEmail\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_d4db37310394c13743df4b8097\` ON \`atollase_db_lucas\`.\`users_projetos_projects\` (\`projectsId\`)`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`projects\` ADD CONSTRAINT \`FK_2f617fc6326d0d2caae50d99297\` FOREIGN KEY (\`userCreatorId\`, \`userCreatorEmail\`) REFERENCES \`atollase_db_lucas\`.\`users\`(\`id\`,\`email\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`activities_questions_questions\` ADD CONSTRAINT \`FK_9e52bef38227dad18c3596a6ae1\` FOREIGN KEY (\`activitiesId\`) REFERENCES \`atollase_db_lucas\`.\`activities\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`activities_questions_questions\` ADD CONSTRAINT \`FK_4fe4be36c0389b6153ebadd1bcb\` FOREIGN KEY (\`questionsId\`) REFERENCES \`atollase_db_lucas\`.\`questions\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`projects_tags_tags\` ADD CONSTRAINT \`FK_0e16f99420fe5a6ae7022afa8b8\` FOREIGN KEY (\`projectsId\`) REFERENCES \`atollase_db_lucas\`.\`projects\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`projects_tags_tags\` ADD CONSTRAINT \`FK_3e919187cc1d287f881fc4f6e4e\` FOREIGN KEY (\`tagsId\`) REFERENCES \`atollase_db_lucas\`.\`tags\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`projects_disciplinas_relacionadas_disciplinas\` ADD CONSTRAINT \`FK_960b3246d9c77e27115d25a68e2\` FOREIGN KEY (\`projectsId\`) REFERENCES \`atollase_db_lucas\`.\`projects\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`projects_disciplinas_relacionadas_disciplinas\` ADD CONSTRAINT \`FK_719413c02395cbc71c6d3cb19ab\` FOREIGN KEY (\`disciplinasId\`) REFERENCES \`atollase_db_lucas\`.\`disciplinas\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`projects_avisos_notices\` ADD CONSTRAINT \`FK_1e4e71740315261703c33079a4c\` FOREIGN KEY (\`projectsId\`) REFERENCES \`atollase_db_lucas\`.\`projects\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`projects_avisos_notices\` ADD CONSTRAINT \`FK_61ef79a2433639d34fb528aaf72\` FOREIGN KEY (\`noticesId\`) REFERENCES \`atollase_db_lucas\`.\`notices\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`projects_atividades_activities\` ADD CONSTRAINT \`FK_ce4725a7c540057981eb547c913\` FOREIGN KEY (\`projectsId\`) REFERENCES \`atollase_db_lucas\`.\`projects\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`projects_atividades_activities\` ADD CONSTRAINT \`FK_974392b318d217b62da32052689\` FOREIGN KEY (\`activitiesId\`) REFERENCES \`atollase_db_lucas\`.\`activities\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`users_projetos_projects\` ADD CONSTRAINT \`FK_c50fdd1f6925679a3e187b9d2c1\` FOREIGN KEY (\`usersId\`, \`usersEmail\`) REFERENCES \`atollase_db_lucas\`.\`users\`(\`id\`,\`email\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`users_projetos_projects\` ADD CONSTRAINT \`FK_d4db37310394c13743df4b80978\` FOREIGN KEY (\`projectsId\`) REFERENCES \`atollase_db_lucas\`.\`projects\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`activities_user_creator_users\` ADD CONSTRAINT \`FK_3c7453ba4344971b2b952a6ac34\` FOREIGN KEY (\`activitiesId\`) REFERENCES \`atollase_db_lucas\`.\`activities\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`activities_user_creator_users\` ADD CONSTRAINT \`FK_3157df03e1c2eeb71f0123fc050\` FOREIGN KEY (\`usersId\`, \`usersEmail\`) REFERENCES \`atollase_db_lucas\`.\`users\`(\`id\`,\`email\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`escopo_steam_steam\` ADD CONSTRAINT \`FK_955d7b3be95dfd1edc986137637\` FOREIGN KEY (\`escopoId\`) REFERENCES \`atollase_db_lucas\`.\`escopo\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`escopo_steam_steam\` ADD CONSTRAINT \`FK_2ae07b5b2a16eaaf18bb173d2de\` FOREIGN KEY (\`steamId\`) REFERENCES \`atollase_db_lucas\`.\`Steam\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`answers_questions_questions\` ADD CONSTRAINT \`FK_3367d6f77c1fcdcefff2022bf46\` FOREIGN KEY (\`answersId\`) REFERENCES \`atollase_db_lucas\`.\`answers\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`answers_questions_questions\` ADD CONSTRAINT \`FK_f5301e03552e125b3a7466abdbb\` FOREIGN KEY (\`questionsId\`) REFERENCES \`atollase_db_lucas\`.\`questions\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`answers_user_creator_users\` ADD CONSTRAINT \`FK_8305e4d21af7fe8895df34786be\` FOREIGN KEY (\`answersId\`) REFERENCES \`atollase_db_lucas\`.\`answers\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`answers_user_creator_users\` ADD CONSTRAINT \`FK_5d25d2520390bc1aa5007d4725c\` FOREIGN KEY (\`usersId\`, \`usersEmail\`) REFERENCES \`atollase_db_lucas\`.\`users\`(\`id\`,\`email\`) ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`answers_user_creator_users\` DROP FOREIGN KEY \`FK_5d25d2520390bc1aa5007d4725c\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`answers_user_creator_users\` DROP FOREIGN KEY \`FK_8305e4d21af7fe8895df34786be\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`answers_questions_questions\` DROP FOREIGN KEY \`FK_f5301e03552e125b3a7466abdbb\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`answers_questions_questions\` DROP FOREIGN KEY \`FK_3367d6f77c1fcdcefff2022bf46\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`escopo_steam_steam\` DROP FOREIGN KEY \`FK_2ae07b5b2a16eaaf18bb173d2de\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`escopo_steam_steam\` DROP FOREIGN KEY \`FK_955d7b3be95dfd1edc986137637\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`activities_user_creator_users\` DROP FOREIGN KEY \`FK_3157df03e1c2eeb71f0123fc050\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`activities_user_creator_users\` DROP FOREIGN KEY \`FK_3c7453ba4344971b2b952a6ac34\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`users_projetos_projects\` DROP FOREIGN KEY \`FK_d4db37310394c13743df4b80978\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`users_projetos_projects\` DROP FOREIGN KEY \`FK_c50fdd1f6925679a3e187b9d2c1\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`projects_atividades_activities\` DROP FOREIGN KEY \`FK_974392b318d217b62da32052689\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`projects_atividades_activities\` DROP FOREIGN KEY \`FK_ce4725a7c540057981eb547c913\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`projects_avisos_notices\` DROP FOREIGN KEY \`FK_61ef79a2433639d34fb528aaf72\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`projects_avisos_notices\` DROP FOREIGN KEY \`FK_1e4e71740315261703c33079a4c\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`projects_disciplinas_relacionadas_disciplinas\` DROP FOREIGN KEY \`FK_719413c02395cbc71c6d3cb19ab\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`projects_disciplinas_relacionadas_disciplinas\` DROP FOREIGN KEY \`FK_960b3246d9c77e27115d25a68e2\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`projects_tags_tags\` DROP FOREIGN KEY \`FK_3e919187cc1d287f881fc4f6e4e\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`projects_tags_tags\` DROP FOREIGN KEY \`FK_0e16f99420fe5a6ae7022afa8b8\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`activities_questions_questions\` DROP FOREIGN KEY \`FK_4fe4be36c0389b6153ebadd1bcb\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`activities_questions_questions\` DROP FOREIGN KEY \`FK_9e52bef38227dad18c3596a6ae1\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`projects\` DROP FOREIGN KEY \`FK_2f617fc6326d0d2caae50d99297\``);
        await queryRunner.query(`DROP INDEX \`IDX_d4db37310394c13743df4b8097\` ON \`atollase_db_lucas\`.\`users_projetos_projects\``);
        await queryRunner.query(`DROP INDEX \`IDX_c50fdd1f6925679a3e187b9d2c\` ON \`atollase_db_lucas\`.\`users_projetos_projects\``);
        await queryRunner.query(`DROP INDEX \`IDX_974392b318d217b62da3205268\` ON \`atollase_db_lucas\`.\`projects_atividades_activities\``);
        await queryRunner.query(`DROP INDEX \`IDX_ce4725a7c540057981eb547c91\` ON \`atollase_db_lucas\`.\`projects_atividades_activities\``);
        await queryRunner.query(`DROP INDEX \`IDX_61ef79a2433639d34fb528aaf7\` ON \`atollase_db_lucas\`.\`projects_avisos_notices\``);
        await queryRunner.query(`DROP INDEX \`IDX_1e4e71740315261703c33079a4\` ON \`atollase_db_lucas\`.\`projects_avisos_notices\``);
        await queryRunner.query(`DROP INDEX \`IDX_3e919187cc1d287f881fc4f6e4\` ON \`atollase_db_lucas\`.\`projects_tags_tags\``);
        await queryRunner.query(`DROP INDEX \`IDX_0e16f99420fe5a6ae7022afa8b\` ON \`atollase_db_lucas\`.\`projects_tags_tags\``);
        await queryRunner.query(`DROP INDEX \`IDX_4fe4be36c0389b6153ebadd1bc\` ON \`atollase_db_lucas\`.\`activities_questions_questions\``);
        await queryRunner.query(`DROP INDEX \`IDX_9e52bef38227dad18c3596a6ae\` ON \`atollase_db_lucas\`.\`activities_questions_questions\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`users_projetos_projects\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`users_projetos_projects\` ADD PRIMARY KEY (\`usersId\`, \`projectsId\`)`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`projects_avisos_notices\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`projects_avisos_notices\` ADD PRIMARY KEY (\`projectsId\`)`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`users_projetos_projects\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`users_projetos_projects\` ADD PRIMARY KEY (\`usersId\`, \`usersEmail\`, \`projectsId\`)`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`projects_avisos_notices\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`projects_avisos_notices\` ADD PRIMARY KEY (\`projectsId\`, \`noticesId\`)`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`users_projetos_projects\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`users_projetos_projects\` ADD PRIMARY KEY (\`usersId\`, \`projectsId\`)`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`projects_avisos_notices\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`projects_avisos_notices\` ADD PRIMARY KEY (\`projectsId\`)`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`questions\` DROP COLUMN \`nota\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`questions\` DROP COLUMN \`tipo\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`questions\` DROP COLUMN \`titulo\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`projects_avisos_notices\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`activities\` DROP COLUMN \`descricao\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`activities\` DROP COLUMN \`titulo\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`activities\` DROP COLUMN \`description\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`activities\` DROP COLUMN \`title\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`questions\` DROP COLUMN \`idQuestion\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`questions\` DROP COLUMN \`title\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`projects_avisos_notices\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`questions\` ADD \`idQuestion\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`questions\` ADD \`title\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`activities\` ADD \`description\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`activities\` ADD \`title\` varchar(255) NOT NULL`);
        await queryRunner.query(`DROP INDEX \`IDX_5d25d2520390bc1aa5007d4725\` ON \`atollase_db_lucas\`.\`answers_user_creator_users\``);
        await queryRunner.query(`DROP INDEX \`IDX_8305e4d21af7fe8895df34786b\` ON \`atollase_db_lucas\`.\`answers_user_creator_users\``);
        await queryRunner.query(`DROP TABLE \`atollase_db_lucas\`.\`answers_user_creator_users\``);
        await queryRunner.query(`DROP INDEX \`IDX_f5301e03552e125b3a7466abdb\` ON \`atollase_db_lucas\`.\`answers_questions_questions\``);
        await queryRunner.query(`DROP INDEX \`IDX_3367d6f77c1fcdcefff2022bf4\` ON \`atollase_db_lucas\`.\`answers_questions_questions\``);
        await queryRunner.query(`DROP TABLE \`atollase_db_lucas\`.\`answers_questions_questions\``);
        await queryRunner.query(`DROP INDEX \`IDX_2ae07b5b2a16eaaf18bb173d2d\` ON \`atollase_db_lucas\`.\`escopo_steam_steam\``);
        await queryRunner.query(`DROP INDEX \`IDX_955d7b3be95dfd1edc98613763\` ON \`atollase_db_lucas\`.\`escopo_steam_steam\``);
        await queryRunner.query(`DROP TABLE \`atollase_db_lucas\`.\`escopo_steam_steam\``);
        await queryRunner.query(`DROP INDEX \`IDX_3157df03e1c2eeb71f0123fc05\` ON \`atollase_db_lucas\`.\`activities_user_creator_users\``);
        await queryRunner.query(`DROP INDEX \`IDX_3c7453ba4344971b2b952a6ac3\` ON \`atollase_db_lucas\`.\`activities_user_creator_users\``);
        await queryRunner.query(`DROP TABLE \`atollase_db_lucas\`.\`activities_user_creator_users\``);
        await queryRunner.query(`DROP INDEX \`IDX_719413c02395cbc71c6d3cb19a\` ON \`atollase_db_lucas\`.\`projects_disciplinas_relacionadas_disciplinas\``);
        await queryRunner.query(`DROP INDEX \`IDX_960b3246d9c77e27115d25a68e\` ON \`atollase_db_lucas\`.\`projects_disciplinas_relacionadas_disciplinas\``);
        await queryRunner.query(`DROP TABLE \`atollase_db_lucas\`.\`projects_disciplinas_relacionadas_disciplinas\``);
        await queryRunner.query(`DROP TABLE \`atollase_db_lucas\`.\`users_projetos_projects\``);
        await queryRunner.query(`DROP TABLE \`atollase_db_lucas\`.\`tecnologias\``);
        await queryRunner.query(`DROP TABLE \`atollase_db_lucas\`.\`answers\``);
        await queryRunner.query(`DROP TABLE \`atollase_db_lucas\`.\`projeto_tecnologia\``);
        await queryRunner.query(`DROP TABLE \`atollase_db_lucas\`.\`projects_tags_tags\``);
        await queryRunner.query(`DROP TABLE \`atollase_db_lucas\`.\`projeto_escopo\``);
        await queryRunner.query(`DROP TABLE \`atollase_db_lucas\`.\`projects_disciplina_disciplinas\``);
        await queryRunner.query(`DROP TABLE \`atollase_db_lucas\`.\`projects_avisos_notices\``);
        await queryRunner.query(`DROP TABLE \`atollase_db_lucas\`.\`projects_atividades_activities\``);
        await queryRunner.query(`DROP TABLE \`atollase_db_lucas\`.\`Escopo_Steam\``);
        await queryRunner.query(`DROP TABLE \`atollase_db_lucas\`.\`escopo_Skills\``);
        await queryRunner.query(`DROP TABLE \`atollase_db_lucas\`.\`escopo_ods\``);
        await queryRunner.query(`DROP TABLE \`atollase_db_lucas\`.\`escopo_disciplinas\``);
        await queryRunner.query(`DROP TABLE \`atollase_db_lucas\`.\`escopo\``);
        await queryRunner.query(`DROP TABLE \`atollase_db_lucas\`.\`skills\``);
        await queryRunner.query(`DROP TABLE \`atollase_db_lucas\`.\`ods\``);
        await queryRunner.query(`DROP TABLE \`atollase_db_lucas\`.\`Steam\``);
        await queryRunner.query(`DROP TABLE \`atollase_db_lucas\`.\`disciplinasEscopo\``);
        await queryRunner.query(`DROP TABLE \`atollase_db_lucas\`.\`activities_questions_questions\``);
        await queryRunner.query(`DROP TABLE \`atollase_db_lucas\`.\`users\``);
        await queryRunner.query(`DROP TABLE \`atollase_db_lucas\`.\`projects\``);
        await queryRunner.query(`DROP TABLE \`atollase_db_lucas\`.\`disciplinas\``);
        await queryRunner.query(`DROP TABLE \`atollase_db_lucas\`.\`notices\``);
        await queryRunner.query(`DROP TABLE \`atollase_db_lucas\`.\`tags\``);
        await queryRunner.query(`DROP TABLE \`atollase_db_lucas\`.\`activities\``);
        await queryRunner.query(`DROP TABLE \`atollase_db_lucas\`.\`questions\``);
    }

}
