import {MigrationInterface, QueryRunner} from "typeorm";

export class updateAvaliacoes1638160419084 implements MigrationInterface {
    name = 'updateAvaliacoes1638160419084'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`projects_atividades_activities\` DROP FOREIGN KEY \`FK_974392b318d217b62da32052689\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`projects_atividades_activities\` DROP FOREIGN KEY \`FK_ce4725a7c540057981eb547c913\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`projects_avisos_notices\` DROP FOREIGN KEY \`FK_1e4e71740315261703c33079a4c\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`projects_avisos_notices\` DROP FOREIGN KEY \`FK_61ef79a2433639d34fb528aaf72\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`projects_tags_tags\` DROP FOREIGN KEY \`FK_0e16f99420fe5a6ae7022afa8b8\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`projects_tags_tags\` DROP FOREIGN KEY \`FK_3e919187cc1d287f881fc4f6e4e\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`users_projetos_projects\` DROP FOREIGN KEY \`FK_c50fdd1f6925679a3e187b9d2c1\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`users_projetos_projects\` DROP FOREIGN KEY \`FK_d4db37310394c13743df4b80978\``);
        await queryRunner.query(`DROP INDEX \`IDX_ce4725a7c540057981eb547c91\` ON \`atollase_db_lucas\`.\`projects_atividades_activities\``);
        await queryRunner.query(`DROP INDEX \`IDX_974392b318d217b62da3205268\` ON \`atollase_db_lucas\`.\`projects_atividades_activities\``);
        await queryRunner.query(`DROP INDEX \`IDX_1e4e71740315261703c33079a4\` ON \`atollase_db_lucas\`.\`projects_avisos_notices\``);
        await queryRunner.query(`DROP INDEX \`IDX_61ef79a2433639d34fb528aaf7\` ON \`atollase_db_lucas\`.\`projects_avisos_notices\``);
        await queryRunner.query(`DROP INDEX \`IDX_0e16f99420fe5a6ae7022afa8b\` ON \`atollase_db_lucas\`.\`projects_tags_tags\``);
        await queryRunner.query(`DROP INDEX \`IDX_3e919187cc1d287f881fc4f6e4\` ON \`atollase_db_lucas\`.\`projects_tags_tags\``);
        await queryRunner.query(`DROP INDEX \`IDX_c50fdd1f6925679a3e187b9d2c\` ON \`atollase_db_lucas\`.\`users_projetos_projects\``);
        await queryRunner.query(`DROP INDEX \`IDX_d4db37310394c13743df4b8097\` ON \`atollase_db_lucas\`.\`users_projetos_projects\``);
        await queryRunner.query(`CREATE TABLE \`atollase_db_lucas\`.\`avaliacoes\` (\`id\` int NOT NULL AUTO_INCREMENT, \`titulo\` varchar(255) NOT NULL, \`descricao\` varchar(255) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`atollase_db_lucas\`.\`projects_avaliacao\` (\`projectsId\` int NOT NULL, \`avaliacaoId\` int NOT NULL, PRIMARY KEY (\`projectsId\`, \`avaliacaoId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`atollase_db_lucas\`.\`avaliacoes_user_creator_users\` (\`avaliacoesId\` int NOT NULL, \`usersId\` int NOT NULL, \`usersEmail\` varchar(255) NOT NULL, INDEX \`IDX_486cb9c7023e8dea5264b6fcb2\` (\`avaliacoesId\`), INDEX \`IDX_75ed34518c75abb46a85ffa7bb\` (\`usersId\`, \`usersEmail\`), PRIMARY KEY (\`avaliacoesId\`, \`usersId\`, \`usersEmail\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`questions\` DROP COLUMN \`titulo\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`questions\` DROP COLUMN \`tipo\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`questions\` DROP COLUMN \`nota\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`activities\` DROP COLUMN \`titulo\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`activities\` DROP COLUMN \`descricao\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`activities\` DROP COLUMN \`title\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`activities\` DROP COLUMN \`description\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`questions\` DROP COLUMN \`title\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`questions\` DROP COLUMN \`idQuestion\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`projects_avisos_notices\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`questions\` ADD \`title\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`questions\` ADD \`idQuestion\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`activities\` ADD \`title\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`activities\` ADD \`description\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`activities\` ADD \`titulo\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`activities\` ADD \`descricao\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`projects_avisos_notices\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`questions\` ADD \`titulo\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`questions\` ADD \`tipo\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`questions\` ADD \`nota\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`users_projetos_projects\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`users_projetos_projects\` ADD PRIMARY KEY (\`usersId\`, \`projectsId\`)`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`projects_avisos_notices\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`projects_avisos_notices\` ADD PRIMARY KEY (\`projectsId\`)`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`users_projetos_projects\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`users_projetos_projects\` ADD PRIMARY KEY (\`usersId\`, \`projectsId\`)`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`projects_avisos_notices\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`projects_avisos_notices\` ADD PRIMARY KEY (\`projectsId\`, \`noticesId\`)`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`users_projetos_projects\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`users_projetos_projects\` ADD PRIMARY KEY (\`usersId\`, \`projectsId\`, \`usersEmail\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_0e16f99420fe5a6ae7022afa8b\` ON \`atollase_db_lucas\`.\`projects_tags_tags\` (\`projectsId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_3e919187cc1d287f881fc4f6e4\` ON \`atollase_db_lucas\`.\`projects_tags_tags\` (\`tagsId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_1e4e71740315261703c33079a4\` ON \`atollase_db_lucas\`.\`projects_avisos_notices\` (\`projectsId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_61ef79a2433639d34fb528aaf7\` ON \`atollase_db_lucas\`.\`projects_avisos_notices\` (\`noticesId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_ce4725a7c540057981eb547c91\` ON \`atollase_db_lucas\`.\`projects_atividades_activities\` (\`projectsId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_974392b318d217b62da3205268\` ON \`atollase_db_lucas\`.\`projects_atividades_activities\` (\`activitiesId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_c50fdd1f6925679a3e187b9d2c\` ON \`atollase_db_lucas\`.\`users_projetos_projects\` (\`usersId\`, \`usersEmail\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_d4db37310394c13743df4b8097\` ON \`atollase_db_lucas\`.\`users_projetos_projects\` (\`projectsId\`)`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`projects_tags_tags\` ADD CONSTRAINT \`FK_0e16f99420fe5a6ae7022afa8b8\` FOREIGN KEY (\`projectsId\`) REFERENCES \`atollase_db_lucas\`.\`projects\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`projects_tags_tags\` ADD CONSTRAINT \`FK_3e919187cc1d287f881fc4f6e4e\` FOREIGN KEY (\`tagsId\`) REFERENCES \`atollase_db_lucas\`.\`tags\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`projects_avisos_notices\` ADD CONSTRAINT \`FK_1e4e71740315261703c33079a4c\` FOREIGN KEY (\`projectsId\`) REFERENCES \`atollase_db_lucas\`.\`projects\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`projects_avisos_notices\` ADD CONSTRAINT \`FK_61ef79a2433639d34fb528aaf72\` FOREIGN KEY (\`noticesId\`) REFERENCES \`atollase_db_lucas\`.\`notices\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`projects_atividades_activities\` ADD CONSTRAINT \`FK_ce4725a7c540057981eb547c913\` FOREIGN KEY (\`projectsId\`) REFERENCES \`atollase_db_lucas\`.\`projects\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`projects_atividades_activities\` ADD CONSTRAINT \`FK_974392b318d217b62da32052689\` FOREIGN KEY (\`activitiesId\`) REFERENCES \`atollase_db_lucas\`.\`activities\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`users_projetos_projects\` ADD CONSTRAINT \`FK_c50fdd1f6925679a3e187b9d2c1\` FOREIGN KEY (\`usersId\`, \`usersEmail\`) REFERENCES \`atollase_db_lucas\`.\`users\`(\`id\`,\`email\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`users_projetos_projects\` ADD CONSTRAINT \`FK_d4db37310394c13743df4b80978\` FOREIGN KEY (\`projectsId\`) REFERENCES \`atollase_db_lucas\`.\`projects\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`avaliacoes_user_creator_users\` ADD CONSTRAINT \`FK_486cb9c7023e8dea5264b6fcb2a\` FOREIGN KEY (\`avaliacoesId\`) REFERENCES \`atollase_db_lucas\`.\`avaliacoes\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`avaliacoes_user_creator_users\` ADD CONSTRAINT \`FK_75ed34518c75abb46a85ffa7bb5\` FOREIGN KEY (\`usersId\`, \`usersEmail\`) REFERENCES \`atollase_db_lucas\`.\`users\`(\`id\`,\`email\`) ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`avaliacoes_user_creator_users\` DROP FOREIGN KEY \`FK_75ed34518c75abb46a85ffa7bb5\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`avaliacoes_user_creator_users\` DROP FOREIGN KEY \`FK_486cb9c7023e8dea5264b6fcb2a\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`users_projetos_projects\` DROP FOREIGN KEY \`FK_d4db37310394c13743df4b80978\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`users_projetos_projects\` DROP FOREIGN KEY \`FK_c50fdd1f6925679a3e187b9d2c1\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`projects_atividades_activities\` DROP FOREIGN KEY \`FK_974392b318d217b62da32052689\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`projects_atividades_activities\` DROP FOREIGN KEY \`FK_ce4725a7c540057981eb547c913\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`projects_avisos_notices\` DROP FOREIGN KEY \`FK_61ef79a2433639d34fb528aaf72\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`projects_avisos_notices\` DROP FOREIGN KEY \`FK_1e4e71740315261703c33079a4c\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`projects_tags_tags\` DROP FOREIGN KEY \`FK_3e919187cc1d287f881fc4f6e4e\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`projects_tags_tags\` DROP FOREIGN KEY \`FK_0e16f99420fe5a6ae7022afa8b8\``);
        await queryRunner.query(`DROP INDEX \`IDX_d4db37310394c13743df4b8097\` ON \`atollase_db_lucas\`.\`users_projetos_projects\``);
        await queryRunner.query(`DROP INDEX \`IDX_c50fdd1f6925679a3e187b9d2c\` ON \`atollase_db_lucas\`.\`users_projetos_projects\``);
        await queryRunner.query(`DROP INDEX \`IDX_974392b318d217b62da3205268\` ON \`atollase_db_lucas\`.\`projects_atividades_activities\``);
        await queryRunner.query(`DROP INDEX \`IDX_ce4725a7c540057981eb547c91\` ON \`atollase_db_lucas\`.\`projects_atividades_activities\``);
        await queryRunner.query(`DROP INDEX \`IDX_61ef79a2433639d34fb528aaf7\` ON \`atollase_db_lucas\`.\`projects_avisos_notices\``);
        await queryRunner.query(`DROP INDEX \`IDX_1e4e71740315261703c33079a4\` ON \`atollase_db_lucas\`.\`projects_avisos_notices\``);
        await queryRunner.query(`DROP INDEX \`IDX_3e919187cc1d287f881fc4f6e4\` ON \`atollase_db_lucas\`.\`projects_tags_tags\``);
        await queryRunner.query(`DROP INDEX \`IDX_0e16f99420fe5a6ae7022afa8b\` ON \`atollase_db_lucas\`.\`projects_tags_tags\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`users_projetos_projects\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`users_projetos_projects\` ADD PRIMARY KEY (\`usersId\`, \`projectsId\`)`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`projects_avisos_notices\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`projects_avisos_notices\` ADD PRIMARY KEY (\`projectsId\`)`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`users_projetos_projects\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`users_projetos_projects\` ADD PRIMARY KEY (\`usersId\`, \`usersEmail\`, \`projectsId\`)`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`projects_avisos_notices\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`projects_avisos_notices\` ADD PRIMARY KEY (\`projectsId\`, \`noticesId\`)`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`users_projetos_projects\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`users_projetos_projects\` ADD PRIMARY KEY (\`usersId\`, \`usersEmail\`, \`projectsId\`)`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`questions\` DROP COLUMN \`nota\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`questions\` DROP COLUMN \`tipo\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`questions\` DROP COLUMN \`titulo\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`projects_avisos_notices\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`activities\` DROP COLUMN \`descricao\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`activities\` DROP COLUMN \`titulo\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`activities\` DROP COLUMN \`description\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`activities\` DROP COLUMN \`title\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`questions\` DROP COLUMN \`idQuestion\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`questions\` DROP COLUMN \`title\``);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`projects_avisos_notices\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`questions\` ADD \`idQuestion\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`questions\` ADD \`title\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`activities\` ADD \`description\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`activities\` ADD \`title\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`activities\` ADD \`descricao\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`activities\` ADD \`titulo\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`questions\` ADD \`nota\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`questions\` ADD \`tipo\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`questions\` ADD \`titulo\` varchar(255) NOT NULL`);
        await queryRunner.query(`DROP INDEX \`IDX_75ed34518c75abb46a85ffa7bb\` ON \`atollase_db_lucas\`.\`avaliacoes_user_creator_users\``);
        await queryRunner.query(`DROP INDEX \`IDX_486cb9c7023e8dea5264b6fcb2\` ON \`atollase_db_lucas\`.\`avaliacoes_user_creator_users\``);
        await queryRunner.query(`DROP TABLE \`atollase_db_lucas\`.\`avaliacoes_user_creator_users\``);
        await queryRunner.query(`DROP TABLE \`atollase_db_lucas\`.\`projects_avaliacao\``);
        await queryRunner.query(`DROP TABLE \`atollase_db_lucas\`.\`avaliacoes\``);
        await queryRunner.query(`CREATE INDEX \`IDX_d4db37310394c13743df4b8097\` ON \`atollase_db_lucas\`.\`users_projetos_projects\` (\`projectsId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_c50fdd1f6925679a3e187b9d2c\` ON \`atollase_db_lucas\`.\`users_projetos_projects\` (\`usersId\`, \`usersEmail\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_3e919187cc1d287f881fc4f6e4\` ON \`atollase_db_lucas\`.\`projects_tags_tags\` (\`tagsId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_0e16f99420fe5a6ae7022afa8b\` ON \`atollase_db_lucas\`.\`projects_tags_tags\` (\`projectsId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_61ef79a2433639d34fb528aaf7\` ON \`atollase_db_lucas\`.\`projects_avisos_notices\` (\`noticesId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_1e4e71740315261703c33079a4\` ON \`atollase_db_lucas\`.\`projects_avisos_notices\` (\`projectsId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_974392b318d217b62da3205268\` ON \`atollase_db_lucas\`.\`projects_atividades_activities\` (\`activitiesId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_ce4725a7c540057981eb547c91\` ON \`atollase_db_lucas\`.\`projects_atividades_activities\` (\`projectsId\`)`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`users_projetos_projects\` ADD CONSTRAINT \`FK_d4db37310394c13743df4b80978\` FOREIGN KEY (\`projectsId\`) REFERENCES \`atollase_db_lucas\`.\`projects\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`users_projetos_projects\` ADD CONSTRAINT \`FK_c50fdd1f6925679a3e187b9d2c1\` FOREIGN KEY (\`usersId\`, \`usersEmail\`) REFERENCES \`atollase_db_lucas\`.\`users\`(\`id\`,\`email\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`projects_tags_tags\` ADD CONSTRAINT \`FK_3e919187cc1d287f881fc4f6e4e\` FOREIGN KEY (\`tagsId\`) REFERENCES \`atollase_db_lucas\`.\`tags\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`projects_tags_tags\` ADD CONSTRAINT \`FK_0e16f99420fe5a6ae7022afa8b8\` FOREIGN KEY (\`projectsId\`) REFERENCES \`atollase_db_lucas\`.\`projects\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`projects_avisos_notices\` ADD CONSTRAINT \`FK_61ef79a2433639d34fb528aaf72\` FOREIGN KEY (\`noticesId\`) REFERENCES \`atollase_db_lucas\`.\`notices\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`projects_avisos_notices\` ADD CONSTRAINT \`FK_1e4e71740315261703c33079a4c\` FOREIGN KEY (\`projectsId\`) REFERENCES \`atollase_db_lucas\`.\`projects\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`projects_atividades_activities\` ADD CONSTRAINT \`FK_ce4725a7c540057981eb547c913\` FOREIGN KEY (\`projectsId\`) REFERENCES \`atollase_db_lucas\`.\`projects\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`atollase_db_lucas\`.\`projects_atividades_activities\` ADD CONSTRAINT \`FK_974392b318d217b62da32052689\` FOREIGN KEY (\`activitiesId\`) REFERENCES \`atollase_db_lucas\`.\`activities\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
    }

}
